# Generated by Django 6.0a1 on 2025-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caravan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the entity', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the entity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('event', models.ForeignKey(help_text='Event associated with the caravan', on_delete=django.db.models.deletion.CASCADE, related_name='caravans', to='event.event')),
                ('vehicle', models.ForeignKey(help_text='Vehicle used for the caravan', on_delete=django.db.models.deletion.CASCADE, related_name='caravans', to='vehicle.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaravanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Leader'), (2, 'Member'), (3, 'Support'), (4, 'Other')], default=2, help_text='Role of the member in the caravan')),
                ('caravan', models.ForeignKey(help_text='Caravan to which the member belongs', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='caravan.caravan')),
                ('user', models.ForeignKey(help_text='User who is a member of the caravan', on_delete=django.db.models.deletion.CASCADE, related_name='caravan_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaravanStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('time', models.DateTimeField(help_text='Scheduled time for the stop')),
                ('type', models.IntegerField(choices=[(0, 'Start'), (1, 'Rest'), (2, 'Refuel'), (3, 'Maintenance'), (4, 'Other'), (5, 'End')], default=4, help_text='Type of the stop')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the stop')),
                ('caravan', models.ForeignKey(help_text='Caravan associated with the stop', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='caravan.caravan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaravanStopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Street address', max_length=200)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State or province', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=20)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude', max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('stop', models.OneToOneField(help_text='Caravan stop associated with the location', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='caravan.caravanstop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
