# Generated by Django 6.0a1 on 2025-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the entity', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the entity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('capacity', models.PositiveSmallIntegerField(help_text='Seating capacity of the vehicle')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Car'), (2, 'Truck'), (3, 'Motorcycle'), (4, 'Bus'), (5, 'Van'), (6, 'Other')], default=4, help_text='Type of the vehicle')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Maintenance'), (4, 'Decommissioned')], default=1, help_text='Current status of the vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Driver'), (2, 'Navigator'), (3, 'Passenger'), (4, 'Mechanic'), (5, 'Other')], default=3, help_text='Role of the user in relation to the vehicle')),
                ('user', models.ForeignKey(help_text='User assigned to the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='Vehicle to which the user is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicle.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('message', models.TextField(blank=True, help_text='Log message', null=True)),
                ('vehicle', models.ForeignKey(help_text='Vehicle associated with the log entry', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vehicle.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
