# Generated by Django 6.0a1 on 2025-09-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the entity', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the entity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Street address', max_length=200)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State or province', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=20)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude', max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('event', models.ForeignKey(help_text='Event associated with the location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('start_datetime', models.DateTimeField(help_text='Start date and time of the event')),
                ('end_datetime', models.DateTimeField(help_text='End date and time of the event')),
                ('event', models.ForeignKey(help_text='Event associated with the schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
